#!/usr/bin/env perl
use Mojo::JSON;
use Mojo::Template;

my $mt = Mojo::Template->new;

open my $fh, '<', 'results.json' or die "No results.json available";
my $json  = do { local $/; <$fh> };
close $fh;

my $results = Mojo::JSON->new->decode($json);

sub sortsub {
    ($a, $b);

    if ($results->{$a}{'test'} == $results->{$b}{'test'}) {
        return lc $a cmp lc $b;
    }

    if ($results->{$a}{'test'} == 0) {
        return 1
    }

    return -1
}

my @list    = sort { sortsub @_ } grep { !/^_/ } keys %$results;
$mt->render_file_to_file('template.tt', 'index.html', $results, \@list);
