#!/usr/bin/env perl
use Mojo::JSON;
use Mojo::Template;

my $mt = Mojo::Template->new;

open my $fh, '<', 'results.json' or die "No results.json available";
my $json  = do { local $/; <$fh> };
close $fh;

my $results = Mojo::JSON->new->decode($json);
$mt->render_file_to_file('template.tt', 'index.html', $results);
